Config:
  Control:
    ADB: /venv/Lib/site-packages/adbutils/binaries/adb.exe
  Emulator:
    Command: emulator
    activity_name: com.u8.sdk.U8UnityContext
    device_control_method: ADB
    device_screenshot_method: ADB
    # or com.hypergryph.arknights
    package_name: com.hypergryph.arknights.bilibili
    # mumu模拟器 127.0.0.1:7555
    # blue stack 127.0.0.1:5555
    # 夜神 127.0.0.1:62001
    serial: 127.0.0.1:62001
  Log:
    level: DEBUG
    #是否在控制台输出日志
    handler: false
    #是否在文件输出日志
    file: true
  Screen:
    #是否保存截图
    enable_screen: true
    #开启则会保存每一张图片
    debug: false
    #截图等待时间
    sleep_time: 3
  System:
    project_path: E:\project\arknight
    pid:
  Ocr:
    #cnocr
    use: cnocr
  Game:
    # 是否关闭游戏 当x分钟内无任务
    closable: true
    minutes: 10
    #若有巫恋在贸易站，则无人机加速该贸易站
    efficient: true
    #基建无人机使用建筑 a表示第几行 b表示第几个
    a: 1
    b: 2
    enable_jijian_schedule: false
    # 基建根据心情自动安排进入宿舍
    auto_sleep: true
    # 若开启自动补全芯片，则会刷精一芯片到xinpian_1，精二芯片到xinpian_2
    xinpian_1: 6
    xinpian_2: 10
  Mail:
    enable_mail: false
    sender:
    authorization:
    receiver:
    host: