# This is a basic workflow to help you get started with Actions

name: "pre-release"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9 # optional
      - name: creat venv
        run: |
          python -m pip install --upgrade pip
          pip install .\tookit\Polygon3-3.0.9.1-cp39-cp39-win_amd64.whl,
          pip install .\tookit\python_Levenshtein-0.12.2-cp39-cp39-win_amd64.whl,
          pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: Install VueCli
        run: npm install -g @vue/cli
      - name: Install Neutralino
        run: npm install -g @neutralinojs/neu
      - name: Install and Build Vue
        run: cd webapp && cd arknight-vue && npm install && npm run vue-build:web

      - name: Install and Build Neutralino
        run: cd webapp && npm install && npm run neu-build
      - name: build pyinstaller
        run: pyinstaller_spec.bat
      - name: Creat Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # GitHub secret token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # Git tag (for automatic releases)
          automatic_release_tag: "latest" # optional
          # Should this release be marked as a pre-release?
          prerelease: true # optional, default is true
          # Release title (for automatic releases)
          title: "Development Build" # optional
          # Assets to upload to the release
          files: webapp/dist/Arknight-Script/*.exe # optional
